---
title: "Week 7 - Class Exercise"
subtitle: "PSY 150: Practice Interpreting Output in Class"
author: "KEY"
date: "`r Sys.Date()`"
output: 
    html_document
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, eval=TRUE)
options(scipen = 999) 
```

------------------------------------------------------------------------

### Load packages

------------------------------------------------------------------------

```{r}
library(tidyverse)
library(broom)
library(here)
library(jtools)
library(janitor)
```

------------------------------------------------------------------------

### Data: `nature_simdata_Cimprich2003.csv`

------------------------------------------------------------------------

```{r}
dat <- read_csv(here("data", "nature_simdata_Cimprich2003.csv")) %>%
  mutate(
    time_point = factor(time_point, levels = c("before","after")),
    nre_interv = factor(nre_interv, levels = c("control","treatment")),
    health_problems = factor(health_problems, levels = c("No","Yes")),
    disease_stage = factor(disease_stage, levels = c(0,1,2)))

```

```{r}
# One continuous predictor
m <- lm(anxiety_score ~ age,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)
```


```{r}
# Two continuous predictors
m <- lm(anxiety_score ~ age + education_yrs,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)
```


```{r}
# One categorical predictor (levels: No, Yes)
m <- lm(anxiety_score ~ health_problems,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)
```

```{r}
# One categorical predictor (levels: 0, 1, 2)
m <- lm(anxiety_score ~ disease_stage,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### Data: `blue_light_sleep_sim_psqi.csv`

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "blue_light_sleep_sim_psqi.csv"), show_col_types = FALSE) %>%
  mutate(
    sex = factor(sex),
    field_study = factor(field_study),
    use_reason = factor(use_reason),
    room_lights_off = factor(room_lights_off),
    device_under_pillow = factor(device_under_pillow),
    sleep_interrupt_check = factor(sleep_interrupt_check), 
    chronotype = factor(chronotype, levels = c("morning", "intermediate", "evening")), 
  )
```

```{r}
# One continuous predictor
m <- lm(sleep_duration_hours ~ device_use_minutes_bedtime,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(sleep_duration_hours ~ device_use_minutes_bedtime + irritability_perweek,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: female, male)
m <- lm(sleep_quality_psqi ~ sex,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: morning, intermediate, evening)
m <- lm(sleep_quality_psqi ~ chronotype,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```


------------------------------------------------------------------------

### Data: `nutrition_academics_sim_N577.csv`

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "nutrition_academics_sim_N577.csv"), show_col_types = FALSE) %>%
  mutate(across(c(sex,race,class_year,breakfast_quality,diet_quality_overall,pre_test_meal,
                  full_time,food_insecure), as.factor)) %>% 
  mutate(breakfast_quality = factor(breakfast_quality, levels = c("poor","average","good")))
```

```{r}

# One continuous predictor
m <- lm(gpa ~ breakfast_days_week,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(gpa ~ breakfast_days_week + alcohol_drinks_week,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: 0, 1 = food insecure)
m <- lm(gpa ~ food_insecure,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: poor, average, good)
m <- lm(biology_test_score ~ breakfast_quality,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### Data: `community_college_persistence_sim_N427.csv`

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "city_college_persistence_sim.csv"),
                       show_col_types = FALSE) |>
  mutate(across(c(gender, race, financial_aid), as.factor)) %>% 
  mutate(
    english_factor = case_when(
      english_proficiency < 3.3 ~ "low",
      english_proficiency < 4.3 ~ "moderate",
      TRUE ~ "high"
    ) %>%
      factor(levels = c("low", "moderate", "high"))
  )

```

```{r}

# One continuous predictor
m <- lm(cumulative_gpa ~ hs_gpa,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(cumulative_gpa ~ hs_gpa + social_self_efficacy,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: female, male)
m <- lm(cumulative_gpa ~ gender,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: low, moderate, high)
m <- lm(cumulative_gpa ~ english_factor,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### Data: `aces_crime_sim_N506_v2.csv`

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", " Kazeem2020_ACEs_crime_SIM.csv"), show_col_types = FALSE) |>
  mutate(
    group = factor(group, levels = c("non_incarcerated","incarcerated")),
    sex = factor(sex),
    ethnicity = factor(ethnicity),
    education_level = factor(education_level,
      levels = c("no_school","<primary","primary","secondary","college","postgrad"),
      ordered = TRUE),
    education_3 = case_when(
      education_level %in% c("no_school","<primary") ~ "less_primary",
      education_level %in% c("secondary") ~ "secondary",
      education_level %in% c("college","postgrad") ~ "college"),
    education_3 = factor(education_3, levels = c("less_primary","secondary","college")))

```

```{r}

# One continuous predictor
m <- lm(criminal_behavior_score ~ age,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(criminal_behavior_score ~ age + ace_war_exposure,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: female, male)
m <- lm(criminal_behavior_score ~ ses_low,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: low, moderate, high)
m <- lm(criminal_behavior_score ~ education_3,
        data = dat)


summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```


------------------------------------------------------------------------

### data: `child_adversity_health_age6_sim_N953.csv`

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "child_adversity_health_age6_sim_N953.csv"), show_col_types = FALSE) |>
  mutate(
    phys_health_index = phys_health_index + 0.369,
    child_male = factor(child_sex),
    child_race = factor(child_race),
    caregiver_marital = factor(caregiver_marital,
                               levels = c("married","never_married","formerly_married")),
    poverty_flag = factor(poverty_flag)
  )

```

```{r}

# One continuous predictor
m <- lm(phys_health_index ~ child_age_years,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(phys_health_index ~ child_age_years + total_adverse_exposures,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: female, male)
m <- lm(phys_health_index ~ child_male,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: married, never_married, formerly_married)
m <- lm(phys_health_index ~ caregiver_marital,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### yoga_mental_health_sim_long_N53.csv

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "yoga_mental_health_sim_long_N53.csv"), show_col_types = FALSE) |>
  mutate(
    pre_post = factor(pre_post, levels = c("pre","post")),
    marital_status = factor(marital_status),
    job_status = factor(job_status),
    income_level = factor(income_level, levels = c("low","average","high"), ordered = TRUE),
    education_level = factor(education_level, levels = c("primary","diploma","university"))
  )

```

```{r}

# One continuous predictor
m <- lm(anxiety_score ~ home_practice_min_per_week,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(anxiety_score ~ home_practice_min_per_week + age,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: married, single)
m <- lm(anxiety_score ~ marital_status,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: primary, diploma, university)
m <- lm(anxiety_score ~ education_level,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```


------------------------------------------------------------------------

### data: `ai_exposure_mental_health_sim_N300.csv`

------------------------------------------------------------------------


```{r}
dat <- readr::read_csv(here("data", "ai_exposure_mental_health_sim_N300.csv"), show_col_types = FALSE) |>
  mutate(
    gender = factor(gender),
    industry = factor(industry),
    job_role = factor(job_role),
    income_bracket = factor(income_bracket, levels = c("low","middle","high"), ordered = TRUE)
  )

```

```{r}

# One continuous predictor
m <- lm(anxiety_level ~ surveillance_level,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(anxiety_level ~ surveillance_level + ai_exposure,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: female, male)
m <- lm(anxiety_level ~ gender,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}

# One categorical predictor (levels: entry, mid, senior)
m <- lm(anxiety_level ~ job_role,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```


------------------------------------------------------------------------

### `cannabis_psych_cognition_sim_N2558.csv`

------------------------------------------------------------------------

```{r}

dat <- readr::read_csv(here("data", "cannabis_psych_cognition_sim_N2558.csv"),
                       show_col_types = FALSE) %>%
  mutate(
    group = factor(group, levels = c("non_user","cannabis_user")),
    gender = factor(gender),
    race = factor(race),
    marital_status = factor(marital_status),
    employment = factor(employment),
    income_bracket = factor(income_bracket),
    smoker = factor(smoker, levels = c(0,1), labels = c("no","yes")),
    binge_month = factor(binge_month, levels = c(0,1), labels = c("no","yes"))
  )


```


```{r}

# One continuous predictor
m <- lm(memory_test ~ use_freq_week,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(memory_test ~ use_freq_week + age,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: no, yes)
m <- lm(memory_test ~ binge_month,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: employed, other, student, unemployed)
m <- lm(memory_test ~ employment,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### epilepsy_exercise_stress_depression_qol_sim_N133.csv

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "epilepsy_exercise_stress_depression_qol_sim_N133.csv"),
                       show_col_types = FALSE) |>
  mutate(
    sex = factor(sex),
    race = factor(race),
    marital_status = factor(marital_status),
    seizure_type = factor(seizure_type),
    exercise_active = factor(exercise_active, levels = c(0,1),
                             labels = c("inactive","active"))
  )

```

```{r}

# One continuous predictor
m <- lm(quality_of_life ~ seizure_freq_month,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(quality_of_life ~ seizure_freq_month + education_yrs,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: indoor, outdoor)
m <- lm(quality_of_life ~ exercise_type,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two categorical predictors (levels: unmarried, married)
m <- lm(quality_of_life ~ exercise_type + marital_status,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### music_stress_daily_sim_N60.csv

------------------------------------------------------------------------

```{r}
                       
dat <- readr::read_csv(here("data", "music_stress_daily_sim_N60.csv"), show_col_types = FALSE) |>
  mutate(
    gender = factor(gender),
    site   = factor(site),
    duration_cat = factor(duration_cat, levels = c("<5","5-20","21-45",">45"), ordered = TRUE),
    music_type = factor(music_type, levels = c("classical","ambient","jazz","pop","rock","hiphop")),
    relaxation_goal = factor(relaxation_goal, levels = c(0,1), labels = c("no","yes")),
    with_others     = factor(with_others, levels = c(0,1), labels = c("alone","with_others")),
    weekend         = factor(weekend, levels = c(0,1), labels = c("weekday","weekend"))
  )

```

```{r}

# One continuous predictor
m <- lm(calmness_rating ~ music_listened_self,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(calmness_rating ~ music_listened_self + workload_today,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: alone, with_others)
m <- lm(calmness_rating ~ with_others,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: classical, ambient, jazz, pop, rock, hiphop)
m <- lm(calmness_rating ~ music_type,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

------------------------------------------------------------------------

### sleep_insomnia_college_sim_N557.csv

------------------------------------------------------------------------

```{r}
dat <- readr::read_csv(here("data", "sleep_insomnia_college_sim_N557.csv"), show_col_types = FALSE) %>%
  mutate(
    across(c(sex, marital_status, education_level, employment_status,
             physical_activity, alcohol_use, smoking), factor),
    insomnia_dx = factor(insomnia_dx, levels = c(0,1), labels = c("no","yes"))
  )


```

```{r}

# One continuous predictor
m <- lm(test_anxiety ~ sleep_quality,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# Two continuous predictors
m <- lm(test_anxiety ~ sleep_quality + workload_hours,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: employed, unemployed)
m <- lm(test_anxiety ~ employment_status,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

```{r}
# One categorical predictor (levels: married, not_married / <2_days, ≥2_days )
m <- lm(test_anxiety ~ marital_status + physical_activity,
        data = dat)

summ(m, model.fit = FALSE, model.info = FALSE, digits = 3)

```

